### ISSUE TITLE
<cmath> does not contain M_PI anymore

### ISSUE THREAD

**Issue by BugsDigger** [MicrosoftDocs/cpp-docs.ru-ru#2]
This part does not work (at least in VC2017):
-------------------------------------------------
#define _USE_MATH_DEFINES // for C++
#include <cmath>
-------------------------------------------------

The only option now is
-------------------------------------------------
#define _USE_MATH_DEFINES
#include <math.h>
-------------------------------------------------

**Comment by CeciAc** [comment]
Hello, @BugsDigger

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://github.com/MicrosoftDocs/cpp-docs/issues/179

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
