### ISSUE TITLE
Link to TechNet under the "Guidance" section returns 404

### ISSUE THREAD

**Issue by MasterMann** [MicrosoftDocs/cpp-docs.ru-ru#35]
Title. Please look into this and fix the link.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8ac840f5-eb3b-455b-472b-85d680a6f6ff
* Version Independent ID: 50510bc9-006c-ee1a-711f-9736736c9069
* Content: [/hotpatch (Создать образ с обновлениями)](https://docs.microsoft.com/ru-ru/cpp/build/reference/hotpatch-create-hotpatchable-image?view=vs-2017)
* Content Source: [docs/build/reference/hotpatch-create-hotpatchable-image.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/build/reference/hotpatch-create-hotpatchable-image.md)
* Product: **visual-cpp**
* GitHub Login: @v-anpasi

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #533](https://github.com/MicrosoftDocs/cpp-docs/issues/533) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @MasterMann ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/533.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
