### ISSUE TITLE
good good good

### ISSUE THREAD

**Issue by NikitaDotIvanov64** [MicrosoftDocs/cpp-docs.ru-ru#38]
Gooooood!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 2f4878b1-5b77-4fa7-1aea-06e7abda0c87
* Version Independent ID: 37011be4-a162-d117-597d-f1a7339deab7
* Content: [Единообразная инициализация и делегирование конструкторов](https://docs.microsoft.com/ru-ru/cpp/cpp/uniform-initialization-and-delegating-constructors?view=vs-2017)
* Content Source: [docs/cpp/uniform-initialization-and-delegating-constructors.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/cpp/uniform-initialization-and-delegating-constructors.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hello, @NikitaDotIvanov64 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continually improve your experience.

Kind regards,
Microsoft DOCS International Team
