### ISSUE TITLE
Misspell name operator %

### ISSUE THREAD

**Issue by watovl** [MicrosoftDocs/cpp-docs.ru-ru#43]
Operator % no modulus. It`s remainder of the division. It different properties.
P.S. Sorry for my English.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bcb3930d-a93c-b80c-1907-598826d5a6c5
* Version Independent ID: 53db4fb3-8f37-8e00-df93-e3e74c69bf89
* Content: [Перегрузка операторов](https://docs.microsoft.com/ru-ru/cpp/cpp/operator-overloading?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DRU-RU%26k%3Dk(ELLIPTICCURVE%2FPoint%3A%3A)%3Bk(operator)%3Bk(Point%3A%3A)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017#feedback)
* Content Source: [docs/cpp/operator-overloading.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/cpp/operator-overloading.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hello, @watovl 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**You can write in your native language to explain the issue better :)** 

Kind regards,
Microsoft DOCS International Team

**Comment by MSDN-WhiteKnight** [comment]
It's a source issue. `%` operator is indeed sometimes referred to as "modulus", but this word is amiguous, because it can also mean the absolute value. It should be changed to "modulo" or "remainder" for more clarity. Then in russian article it would be translated as "остаток"

**Comment by mikeblome** [comment]
@MSDN-WhiteKnight We have to keep the English term "modulus" because that is the term used in the language specification and is also the common English name for the operator, regardless of whether it is mathematically correct. @CeciAc I suggest this is an issue that can be addressed by the people responsible for the Russian translation of the documentation.

**Comment by CeciAc** [comment]
Thanks all for your feedback, 
I'll process this issue as usual

Kind regards,

**Comment by CeciAc** [comment]
Hello @watovl 

Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/cpp/cpp/operator-overloading?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DRU-RU%26k%3Dk(ELLIPTICCURVE%2FPoint%3A%3A)%3Bk(operator)%3Bk(Point%3A%3A)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017#feedback 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
